library(tidyverse)
library(readxl)
library(data.table)
library(RColorBrewer)

#set up a nice color palet for use later. 
mypal = c(brewer.pal(8, "Dark2"), brewer.pal(8, "Set3"))

#read in data (from the file generated by microsoft forms)
results = read_excel("data/Data Science PWT poll.xlsx")

#Split up the results into multiple topics
results = mutate(results, topics = str_split(`What general topics are you most interested in?`, ";")) 

#unnest the nested data frame version
unresults = unnest(results, cols = topics) %>%
  filter(topics != "") %>%
  #consolidate some of the topics
  mutate(topics = case_when(topics %in% c("AI/ML application examples? [admittedly broad, this could be mean anything]",
                                          "AI Object Detection and ", "Machine learning") ~ "Machine Learning and AI",
                            TRUE ~ topics))

#summarize the data
piresults = group_by(unresults, topics) %>%
  summarize(N = n())


#bar chart
ggplot(piresults, aes(x = topics, y = N, fill = topics)) + 
  geom_bar(color = "grey29", stat = "identity")+theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust =1, vjust = 0.5))+
  scale_fill_manual(values = mypal, guide = NULL)

#stacked bar chart
ggplot(piresults, aes(x = 1, y = N, fill = topics)) + 
  geom_bar(position = "fill", color = "grey29", stat = "identity")+
  scale_fill_manual(values = mypal, guide = NULL)+
  theme_bw()+
  xlab(NULL)+
  theme(axis.text.x = element_blank())


#base R pie chart

pie(piresults$N, labels = piresults$topics, col = mypal)

#set up labels for ggplot version of ppie chart
pi2 <- piresults %>% 
  arrange(desc(topics)) %>%
  mutate(prop = N / sum(piresults$N) *100) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop )

# Basic piechart
ggplot(pi2, aes(x=2, y=prop, fill=topics)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  theme(legend.position="none") +
  
  geom_text(aes(y = ypos, label = topics),  size=3) +
  scale_fill_manual(values = mypal, guide = NULL)+
  theme_void()

# Donut chart
ggplot(pi2, aes(x=2, y=prop, fill=topics)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  theme(legend.position="none") +
  
  geom_text(aes(y = ypos, label = topics),  size=3) +
  scale_fill_manual(values = mypal, guide = NULL)+
  theme_void()+
  xlim(.5,10)



